### ISSUE TITLE
Does this repo need to persist?

### ISSUE THREAD

**Issue by jmandel** [RSNA/introspection-service#1]
Given that this repo is a fork of https://github.com/sync-for-science/token-introspector, do we need to maintain it here? I'm thinking that we might:

1. Identity any necessary changes and merge them upstream
2. Avoid maintaining a public fork here

I'm not sure there are any necessary changes in (1), but it'd be good to talk through this.

**Comment by kelseym** [comment]
It looks like there are minor changed in the views/api/views.py file and major changes in Dockerfile and README.md files, relating to how this service integrates with the RSNA s4s-stack.  If we want to avoid the current duplication, maybe the right approach is to move these changes onto a branch and tag it in the original repo.

**Comment by jmandel** [comment]
If any of these are required change, we can merge upstream.  In particular though, my understanding is that the `views.py` changes shouldn't be needed. Can you confirm?

**Comment by kelseym** [comment]
It looks like the fhir-broker expects the patient object as JSON and a scope parameter. So those changed would need to persist to maintain compatibility with the current stack.

**Comment by jmandel** [comment]
The complete diff is at https://github.com/RSNA/introspection-service/compare/d6708bc8...master -- and I don't see any functional changes re: scopes or json encoding. Please let me know if I'm missing something?

Re: Dockerfile changes, rather than relying to hard coded server URLs in the Dockerfile, it would be good to make sure that the docker-compose file in the reference stack just injects these values as environment variables. Does that make sense?

**Comment by kelseym** [comment]
My mistake - you are correct. I was comparing the wrong versions. 

Re: In particular though, my understanding is that the views.py changes shouldn't be needed. Can you confirm?

**Comment by jmandel** [comment]
I agree. I think the dockerfile shouldn't change either except perhaps to declare variables if there are any missing. Ideally we wouldn't rely on actual values from this file in a real deployment.

**Comment by kelseym** [comment]
I suppose the API_SERVER value changes and EXPOSE 5000 directive could live in the top level docker-compose file. Is that how you would handle those changes?

**Comment by jmandel** [comment]
Precisely :-)

**Comment by kelseym** [comment]
The RSNA project is now setup to use code directly from https://github.com/sync-for-science/token-introspector in place of this repo.  Does the S4S team maintain a token-introspector Docker image as well? If so, we can incorporate that directly rather than build one in Docker Hub.

**Comment by kelseym** [comment]
Our docker-compose file now uses the syncforscience/token-introspector Docker image directly.

**Comment by jmandel** [comment]
Perfect! I think we can retirement this repo.
